import { Event } from './event';
import { createReportURL } from './report';
import { log } from './logger';
import { Run } from './run';
import { CompareOutput } from './compare';

export type CreateCommentWithTargetInput = {
  event: Event;
  currentRun: Run;
  targetRun: Run;
  result: CompareOutput;
};

const isSuccess = (result: CompareOutput) => {
  return result.failedItems.length === 0 && result.newItems.length === 0 && result.deletedItems.length === 0;
};

const badge = (result: CompareOutput) => {
  if (result.failedItems.length) {
    return '![change detected](https://img.shields.io/badge/%E2%9C%94%20reg-change%20detected-orange)';
  }
  if (result.newItems.length) {
    return '![new items](https://img.shields.io/badge/%E2%9C%94%20reg-new%20items-green)';
  }
  return '![success](https://img.shields.io/badge/%E2%9C%94%20reg-passed-green)';
};

export const createCommentWithTarget = ({
  event,
  currentRun,
  targetRun,
  result,
}: CreateCommentWithTargetInput): string => {
  const [owner, reponame] = event.repository.full_name.split('/');
  const url = createReportURL(owner, reponame, currentRun.id);
  log.info(`This report URL is ${url}`);

  const currentHash = currentRun.head_sha;
  const targetHash = targetRun.head_sha;
  const currentHashShort = currentHash.slice(0, 7);
  const targetHashShort = targetHash.slice(0, 7);

  const successOrFailMessage = isSuccess(result)
    ? `${badge(result)}
  
  ✨✨ That's perfect, there is no visual difference! ✨✨
  Check out the report [here](${url}).
    `
    : `${badge(result)}
  
  Check out the report [here](${url}).
    `;

  const body = `This report was generated by comparing [${currentHashShort}](https://github.com/${owner}/${reponame}/commit/${currentHash}) and [${targetHashShort}](https://github.com/${owner}/${reponame}/commit/${targetHash}).
  If you would like to check difference, please check [here](https://github.com/${owner}/${reponame}/compare/${currentHashShort}..${targetHashShort}).
  
  ${successOrFailMessage}
  
  | item    | count                         |
  |:--------|:-----------------------------:|
  | pass    | ${result.passedItems.length}  |
  | change  | ${result.failedItems.length}  |
  | new     | ${result.newItems.length}     |
  | delete  | ${result.deletedItems.length} |
  `;

  return body;
};
