import { join, basename } from 'path';

import { Event } from './event';
import { Run } from './run';
import { CompareOutput } from './compare';

export type CreateCommentWithTargetInput = {
  event: Event;
  runId: number;
  sha: string;
  regBranch: string;
  artifactName: string;
  targetRun: Run;
  result: CompareOutput;
};

export type CreateCommentWithoutTargetInput = {
  event: Event;
  runId: number;
  result: CompareOutput;
};

const isSuccess = (result: CompareOutput) => {
  return result.failedItems.length === 0 && result.newItems.length === 0 && result.deletedItems.length === 0;
};

const badge = (result: CompareOutput) => {
  if (result.failedItems.length) {
    return '![change detected](https://img.shields.io/badge/%E2%9C%94%20reg-change%20detected-orange)';
  }
  if (result.newItems.length) {
    return '![new items](https://img.shields.io/badge/%E2%9C%94%20reg-new%20items-green)';
  }
  return '![success](https://img.shields.io/badge/%E2%9C%94%20reg-passed-green)';
};

const createBaseUrl = ({
  owner,
  repoName,
  branch,
  runId,
  artifactName,
}: {
  owner: string;
  repoName: string;
  branch: string;
  runId: number;
  artifactName: string;
}): string => {
  return `https://raw.githubusercontent.com/${owner}/${repoName}/${branch}/${runId}_${artifactName}/`;
};

const differences = ({ result, baseUrl }: { result: CompareOutput; baseUrl: string }): string => {
  if (result.failedItems.length === 0) return '';
  const comment = `   
     
### Differences
  
| Actual     | Expected   | Difference |
|:----------:|:----------:|:----------:|
${result.failedItems
  .map(item => {
    const filename = basename(item);
    return `| ![Actual](${join(baseUrl, 'actual', filename)}) | ![Expected](${join(
      baseUrl,
      'expected',
      filename,
    )}) | ![Difference](${join(baseUrl, 'diff', filename)})|`;
  })
  .join('\n')}
  `;

  return comment;
};

const newItems = ({ result, baseUrl }: { result: CompareOutput; baseUrl: string }): string => {
  if (result.newItems.length === 0) return '';
  const comment = `   
     
### New Items
  
| New Items     | 
|:----------:|
${result.newItems
  .map(item => {
    const filename = basename(item);
    console.log(join(baseUrl, 'actual', filename));

    return `![NewItem](${join(baseUrl, 'actual', filename)})`;
  })
  .join('\n')}
  `;

  return comment;
};

const deletedItems = ({ result, baseUrl }: { result: CompareOutput; baseUrl: string }): string => {
  if (result.deletedItems.length === 0) return '';
  const comment = `   
   
### Deleted Items
  
| Deleted Items     | 
|:----------:|
${result.deletedItems
  .map(item => {
    const filename = basename(item);
    return `| ![Deleted](${join(baseUrl, 'expected', filename)}) |`;
  })
  .join('\n')}
  `;

  return comment;
};

export const createCommentWithTarget = ({
  event,
  runId,
  regBranch,
  artifactName,
  sha: currentHash,
  targetRun,
  result,
}: CreateCommentWithTargetInput): string => {
  const [owner, repoName] = event.repository.full_name.split('/');
  const targetHash = targetRun.head_sha;
  const currentHashShort = currentHash.slice(0, 7);
  const targetHashShort = targetHash.slice(0, 7);
  const baseUrl = createBaseUrl({ owner, repoName, branch: regBranch, runId, artifactName });
  const successOrFailMessage = isSuccess(result)
    ? `${badge(result)}
  
✨✨ That's perfect, there is no visual difference! ✨✨
    `
    : `${badge(result)}
    `;

  const body = `This report was generated by comparing [${currentHashShort}](https://github.com/${owner}/${repoName}/commit/${currentHash}) with [${targetHashShort}](https://github.com/${owner}/${repoName}/commit/${targetHash}).
If you would like to check difference, please check [here](https://github.com/${owner}/${repoName}/compare/${targetHashShort}..${currentHashShort}).
  
${successOrFailMessage}
  
| item    | count                         |
|:--------|:-----------------------------:|
| pass    | ${result.passedItems.length}  |
| change  | ${result.failedItems.length}  |
| new     | ${result.newItems.length}     |
| delete  | ${result.deletedItems.length} |

<details>
<summary>📝 Report</summary>
${differences({ result, baseUrl })}
${newItems({ result, baseUrl })}
${deletedItems({ result, baseUrl })}
</details>
`;

  return body;
};

export const createCommentWithoutTarget = ({ event, runId, result }: CreateCommentWithoutTargetInput): string => {
  const body = `Failed to find a target artifact.
All items will be treated as new items and will be used as expected data for the next time.

![target not found](https://img.shields.io/badge/%E2%9C%94%20reg-new%20items-blue)

| item    | count                         |
|:--------|:-----------------------------:|
| new     | ${result.newItems.length}     |
  `;

  return body;
};
